//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int fileID { get; set; }
        public int parentId { get; set; }
        public string filename { get; set; }
        public Nullable<int> size { get; set; }
        public bool isDirectory { get; set; }
        public string modifydate { get; set; }
        public Nullable<int> lastNodeID { get; set; }
    }
}
